version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered the build phase"
      - ./gradlew clean build
  post_build:
    commands:
      - echo "Entered in post build phase"
artifacts:
  files:
    - build/libs/community-connect-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes
